import type { Campaign, CampaignBrief } from '@/lib/types'
import { createCampaignFromBrief, generateCampaign, baseUrl } from '@/lib/engine/generate'
import { generateGoogleAdsReadiness } from '@/lib/engine/google-ads'
import { runQa } from '@/lib/engine/qa'
import { computeBlockers } from '@/lib/engine/blockers'
import { addVersion } from '@/lib/versioning'

/**
 * Demo/sample campaign data (master spec §56) so the Studio isn't empty on
 * first run. Clearly flagged `isDemo: true` — these are illustrative
 * campaigns, not real Raven Labs Google Ads campaigns, and every fact in
 * them is either generated by the same engine a real campaign would use or
 * (for NABERS) carried over from the real research already on file in
 * HANDOFF.md for that campaign. No fabricated client claims are included.
 */
const demoBriefs: CampaignBrief[] = [
  {
    name: 'NABERS Rating Tracking',
    service: 'NABERS rating tracking software',
    audience: 'Facilities and sustainability managers at commercial building owners',
    industry: 'Commercial real estate',
    geography: 'Australia',
    objective: 'Generate qualified leads via Google Ads for Fulqrom, live NABERS rating tracking software',
    primaryIntent: 'nabers rating tracking software',
    primaryCTA: 'Book my free NABERS health check',
    offer: 'Free NABERS health check',
  },
  {
    name: 'Salesforce Consulting',
    service: 'Salesforce consulting',
    audience: 'US mid-market businesses',
    industry: 'B2B services',
    geography: 'United States',
    objective: 'Generate qualified leads for Salesforce implementation and optimisation services',
    primaryIntent: 'salesforce consulting',
    primaryCTA: 'Get my free Salesforce assessment',
    offer: 'Free Salesforce assessment',
  },
  {
    name: 'AI Automation',
    service: 'AI workflow automation',
    audience: 'Operations leaders at mid-market companies',
    industry: 'Professional services',
    geography: 'Australia',
    objective: 'Generate qualified leads for AI-driven workflow automation projects',
    primaryIntent: 'ai automation services',
    primaryCTA: 'Book my free automation audit',
    offer: 'Free automation audit',
  },
  {
    name: 'Dynamics 365 Consulting',
    service: 'Dynamics 365 consulting',
    audience: 'Enterprise IT and operations teams',
    industry: 'Manufacturing & distribution',
    geography: 'Australia',
    objective: 'Generate qualified leads for Dynamics 365 implementation and migration',
    primaryIntent: 'dynamics 365 consulting',
    primaryCTA: 'Book my free Dynamics 365 consultation',
    offer: 'Free Dynamics 365 consultation',
  },
]

export function buildDemoCampaigns(): Campaign[] {
  const campaigns = demoBriefs.map((brief) => {
    let campaign = createCampaignFromBrief(brief)
    campaign.isDemo = true
    campaign = generateCampaign(campaign)
    campaign = addVersion(campaign, 'Initial generation (demo data)', 'AI generation engine')
    return campaign
  })

  const [nabers, salesforce, aiAutomation, dynamics] = campaigns

  // NABERS: carry over the real research + copy already produced and
  // human-reviewed in this repo's history (HANDOFF.md) instead of the
  // generic templated output, and mark it further along its lifecycle
  // (matches HANDOFF.md: "Draft — ready for human review, not launched").
  nabers.heroVisual = 'nabers-dashboard'
  nabers.primaryKeyword = 'NABERS rating'
  nabers.secondaryKeywords = ['NABERS assessor', 'NABERS rating requirements', 'NABERS rating for offices']
  nabers.competitors = [
    {
      id: 'ark-resources',
      company: 'Ark Resources',
      positioning: 'Full-service ESD consultancy (NatHERS, NABERS, Green Star, embodied carbon), Melbourne, 25+ yrs, 1,500+ projects',
      offer: 'One-off assessments, IDR, ratings submissions',
      differentiationOpportunity: 'Manual, project-based — no continuous/software offering.',
    },
    {
      id: 'certified-energy',
      company: 'Certified Energy',
      positioning: 'Large ESD consultancy, broad service menu (Section J, BASIX, NatHERS, NABERS, JV3)',
      offer: 'Consulting reports',
      differentiationOpportunity: 'No live tracking between assessments.',
    },
    {
      id: 'ausnviro',
      company: 'Ausnviro',
      positioning: 'NABERS energy/water/waste/IER assessments + "Monthly NABERS Tracking" (Mtrack) reports',
      offer: 'Monthly manual tracking reports',
      differentiationOpportunity: 'Closest competitor to "continuous tracking" but still a manual, consultant-produced report cycle (monthly, not live).',
    },
  ]
  if (nabers.copy) {
    nabers.copy.hero = {
      headline: 'Track Your NABERS Rating Live — Before It Drops, Not After',
      subheadline:
        'Fulqrom gives Australian commercial building owners and facilities managers a live NABERS star rating, tracked continuously in software — so you catch problems months before your next official assessment, not after.',
      microcopy: '15 minutes. No obligation. See your live rating first.',
    }
    nabers.copy.problem = {
      headline: "Your NABERS rating is a once-a-year guess — until it isn't",
      body: "Most building owners find out their NABERS star rating has slipped only when the annual assessment comes back low. Chasing twelve months of utility bills after the fact doesn't tell you which month, which plant, or which tenancy caused the drop.",
    }
    nabers.copy.faq.items = [
      { q: 'What is a NABERS rating?', a: 'NABERS is a star rating, out of 6, that measures a building’s energy efficiency against government benchmarks using actual 12-month utility consumption data.' },
      { q: 'Does Fulqrom replace my accredited NABERS assessor?', a: 'No. Fulqrom tracks your rating continuously between assessments so you walk into your next official assessment with clean data. Your accredited assessor still issues the certified rating.' },
      { q: 'How much does Fulqrom cost?', a: 'Pricing depends on your building’s size, meter count, and portfolio. Book a free health check and we’ll scope a fixed quote afterwards — no obligation.' },
      { q: 'How long does setup take?', a: 'Most buildings are live within two weeks of connecting utility retailer data, meters, or BMS feeds — no hardware replacement required.' },
    ]
  }
  nabers.seo = { ...nabers.seo!, title: 'Live NABERS Rating Tracking | Fulqrom', metaDescription: nabers.copy!.hero.subheadline.slice(0, 155) }
  nabers.googleAds = generateGoogleAdsReadiness(nabers, baseUrl())
  nabers.qa = runQa(nabers)
  nabers.blockers = computeBlockers(nabers)

  // Salesforce: already generated + "deployed" (no Vercel creds in this
  // environment, so honestly PENDING_AUTHORIZATION rather than a fabricated
  // live deployment — see lib/actions/campaigns.ts `publishCampaign`).
  salesforce.deployment.status = 'PENDING_AUTHORIZATION'
  salesforce.deployment.log.push({
    at: new Date().toISOString(),
    message: 'Publish requested — VERCEL_TOKEN / VERCEL_PROJECT_ID not set, prepared but not authorized.',
  })
  salesforce.status = 'QA'

  // AI Automation: left as an early draft (not yet generated further than
  // the initial pass) to show the dashboard's DRAFT state.
  aiAutomation.status = 'DRAFT'

  // Dynamics 365: archived, to demonstrate the archive/restore lifecycle.
  dynamics.status = 'ARCHIVED'
  dynamics.archivedAt = new Date().toISOString()
  ;(dynamics as Campaign & { _preArchiveStatus?: string })._preArchiveStatus = 'QA'

  return [nabers, salesforce, aiAutomation, dynamics]
}
